"""
Utility functions for Red-Black Tree operations
"""

def generate_rbt_key(timestamp, unique_id=0):
    """
    Generate a unique key for RBT insertion
    
    Args:
        timestamp: datetime object or timestamp
        unique_id: Unique identifier to ensure uniqueness
        
    Returns:
        float key combining timestamp and id
    """
    if hasattr(timestamp, 'timestamp'):
        ts = int(timestamp.timestamp())
    else:
        ts = float(timestamp)
    
    # Combine timestamp and unique_id for guaranteed uniqueness
    # Format: timestamp.unique_id (e.g., 1700000000.123)
    return float(f"{ts}.{unique_id:03d}")

def extract_timestamp_from_key(key):
    """
    Extract timestamp from RBT key
    
    Args:
        key: RBT key generated by generate_rbt_key
        
    Returns:
        timestamp as float
    """
    return float(str(key).split('.')[0])

def create_time_range_keys(start_time, end_time):
    """
    Create keys for time range search
    
    Args:
        start_time: Start datetime
        end_time: End datetime
        
    Returns:
        Tuple of (start_key, end_key)
    """
    start_key = generate_rbt_key(start_time, 0)
    end_key = generate_rbt_key(end_time, 999)  # Max ID for end range
    
    return start_key, end_key

def validate_time_range(start_time, end_time):
    """
    Validate time range
    
    Args:
        start_time: Start datetime
        end_time: End datetime
        
    Returns:
        bool: True if valid, False otherwise
    """
    if start_time >= end_time:
        return False, "Start time must be before end time"
    
    if (end_time - start_time).total_seconds() > 24 * 3600:  # 24 hours
        return False, "Time range cannot exceed 24 hours"
    
    return True, "Valid time range"